export const DASHBOARD = {
  CHANGE_USER_COURSEPACKS: 'CHANGE_USER_COURSEPACKS',
  UPDATE_USER_COURSEPACKS_DATA: 'UPDATE_USER_COURSEPACKS_DATA',
  UPDATE_USER_COURSEPACKS_LENGTH: 'UPDATE_USER_COURSEPACKS_LENGTH',
};
