export const DASHBOARD = {
  CHANGE_USER_COURSEPACKS: 'CHANGE_USER_COURSEPACKS',
  UPDATE_USER_COURSEPACKS_DATA: 'UPDATE_USER_COURSEPACKS_DATA',
  UPDATE_USER_COURSEPACKS_LENGTH: 'UPDATE_USER_COURSEPACKS_LENGTH',
  CHANGE_COURSES: 'CHANGE_COURSES',
  UPDATE_COURSE_DATA: 'UPDATE_COURSE_DATA',
  UPDATE_COURSES_LENGTH: 'UPDATE_COURSES_LENGTH',
  CHANGE_POPUP_DATA: 'CHANGE_POPUP_DATA',
  CHANGE_SELECTED_COURSEPACK: 'CHANGE_SELECTED_COURSEPACK',
  CHANGE_SELECTED_COURSE: 'CHANGE_SELECTED_COURSE'
};
