export const DASHBOARD = {
  CHANGE_USER_COURSEPACKS: 'CHANGE_USER_COURSEPACKS',
  UPDATE_USER_COURSEPACKS_DATA: 'UPDATE_USER_COURSEPACKS_DATA',
  UPDATE_USER_COURSEPACKS_LENGTH: 'UPDATE_USER_COURSEPACKS_LENGTH',
  REMOVE_COURSEPACK: 'REMOVE_COURSEPACK',
  CHANGE_COURSES: 'CHANGE_COURSES',
  UPDATE_COURSE_DATA: 'UPDATE_COURSE_DATA',
  UPDATE_COURSES_LENGTH: 'UPDATE_COURSES_LENGTH',
  REMOVE_COURSE: 'REMOVE_COURSE',
  CHANGE_LESSONS: 'CHANGE_LESSONS',
  UPDATE_LESSON_DATA: 'UPDATE_LESSON_DATA',
  UPDATE_LESSONS_LENGTH: 'UPDATE_LESSONS_LENGTH',
  REMOVE_LESSON: 'REMOVE_LESSON',
  CHANGE_POPUP_DATA: 'CHANGE_POPUP_DATA',
  CHANGE_SELECTED_COURSEPACK: 'CHANGE_SELECTED_COURSEPACK',
  CHANGE_SELECTED_COURSE: 'CHANGE_SELECTED_COURSE'
};
